name: Lint
on: [push]
jobs:
  fmt:
    name: terraform fmt check
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: terraform fmt check
        run: terraform fmt -check -diff
  lint:
    name: Lint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Cache the tflint plugins directory
        uses: actions/cache@v4
        with:
          path: ~/.tflint.d/plugins
          key: tflint-${{ hashFiles('.tflint.hcl') }}
      - uses: terraform-linters/setup-tflint@v4
        name: Setup
        with:
          tflint_version: v0.49.0
      - name: Init
        run: tflint --init
        env:
          # https://github.com/terraform-linters/tflint/blob/master/docs/user-guide/plugins.md#avoiding-rate-limiting
          GITHUB_TOKEN: ${{ github.token }}
      - name: Lint
        run: tflint --format compact
